### ISSUE TITLE
Pass context to partials

### ISSUE THREAD

**Issue by nicklauslittle** [horseshoe/horseshoe#59]
When invoking partials, it would be useful to be able to pass a context into the partial, similar to how named expressions work. This can be done currently using the following syntax: `{{# newContext }}{{> partial }}{{/}}`. However, this tends to clutter the template with extra tags. Something like `{{> partial(newContext) }}` would be much nicer.

**Comment by tbateson** [comment]
Hijacking this issue to advocate for something a little different. What if instead of piggy-backing off the terrible semantics of Mustache's partials we added a different way to do them, called snippets. Doing this would allow us to fix some of the line ending problems that are present with Mustache partials.
```horseshoe
{{<< snippet(value1, value2, value3) }} <-- standalone tag
  {{ value1 }} = {{ value2 }} + {{ value3 }};
{{/ snippet }}                          <--- standalone tag
```
Which would be functionally equivalent to:
```horseshoe
{{<< snippet(value1, value2, value3) }}  {{ value1 }} = {{ value2 }} + {{ value3 }};{{/snippet}}
```
Given that this isn't the case with Horseshoe's Mustache partials, this would provide a better user experience all around.

**Comment by nicklauslittle** [comment]
I'm a little confused. Are you talking about standalone-ness of the tags, or are you just advocating for parameters on partials? I like the second idea, but I'm not seeing any issues with standalone-ness.

Closing inline partial tags are always considered standalone, so if the only issue is the trailing newline, then you can do
```horseshoe
{{< snippet(value1, value2, value3) }} <-- standalone tag
  {{ value1 }} = {{ value2 }} + {{ value3 }};{{/ snippet }}
{{!/ snippet }}
```
to keep it all on the same line.
